version: '3.1'

services:
  hk-kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    hostname: localhost
    container_name: kafka
    environment:
      - "ADVERTISED_HOST=localhost"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATED_TOPICS=true"
    networks:
      - ecommerceNetwork


  couchbase:
    image: couchbase
    container_name: basketProductDB
    deploy:
      replicas: 1
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210



networks:
  ecommerceNetwork:
    driver: bridge