server:
  port : 8082

promotion-values:
  null-value: -1

topic-names:
  add-promotion: add-promotion
  delete-promotion: delete-promotion
  basket-updated: basket-updated
  promotion-is-over: promotion-is-over
  promotion-list-changed: promotion-list-changed

couchbase-config:
  connection-string: localhost
  user-name: Administrator
  password: password
  bucket-name: Promotions