server:
  port : 8080

topic-names:
  user-made-add-basket-operation: user-made-add-basket-operation
  user-made-update-basket-operation: user-made-update-basket-operation
  user-made-delete-basket-operation: user-made-delete-basket-operation


couchbase-config:
  connection-string: localhost
  user-name: Administrator
  password: password
  bucket-name: BasketProducts